name: 'release'

on:
  push:
    tags:
    - v*

jobs:
  release:
    uses: robvanderleek/repo-meister/.github/workflows/java-maven-release-to-nexus.yml@main
    secrets:
      gpg_private_key: ${{ secrets.gpg_private_key }}
